name: Svelte CI

on: [push, pull_request]

jobs:
  install:
    runs-on: self-hosted
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install Svelte and its dependencies
      - run: | 
            nvm use 18.12.1 --if-present --prefix /home/ubuntu/aleks-portfolio/
            npm install --if-present --prefix /home/ubuntu/aleks-portfolio/
      - uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules

  npm-ci:
    needs: [install]
    runs-on: self-hosted
    steps:
      # Restore the installed dependencies from the previous step
      - uses: actions/download-artifact@v1
        with:
          name: node_modules

      - run: npm ci --if-present --prefix /home/ubuntu/aleks-portfolio/

  test:
    needs: [install]
    runs-on: self-hosted
    steps:
      # Restore the installed dependencies from the previous step
      - uses: actions/download-artifact@v1
        with:
          name: node_modules

      # Run the Svelte tests
      - run: npm test --if-present --prefix /home/ubuntu/aleks-portfolio/

  build:
    needs: [install]
    runs-on: self-hosted
    steps:
      # Restore the installed dependencies from the previous step
      - uses: actions/download-artifact@v1
        with:
          name: node_modules

      # Build the Svelte app
      - run: npm run dev -- --host --if-present --prefix /home/ubuntu/aleks-portfolio/
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: public
